export const MOHS_SCALE = [
  { value: "1", label: "1 — Тальк" },
  { value: "1.5", label: "1.5" },
  { value: "2", label: "2 — Гипс" },
  { value: "2.5", label: "2.5" },
  { value: "3", label: "3 — Кальцит" },
  { value: "3.5", label: "3.5" },
  { value: "4", label: "4 — Флюорит" },
  { value: "4.5", label: "4.5" },
  { value: "5", label: "5 — Апатит" },
  { value: "5.5", label: "5.5" },
  { value: "6", label: "6 — Ортоклаз" },
  { value: "6.5", label: "6.5" },
  { value: "7", label: "7 — Кварц" },
  { value: "7.5", label: "7.5" },
  { value: "8", label: "8 — Топаз" },
  { value: "8.5", label: "8.5" },
  { value: "9", label: "9 — Корунд" },
  { value: "9.5", label: "9.5" },
  { value: "10", label: "10 — Алмаз" }
]